development:
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: enrollments
  password: enrollments
  database: enrollments_development

test:
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: enrollments
  password: enrollments
  database: enrollments_test

production:
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: enrollments
  password: enrollments
  database: enrollments_production
